### ISSUE TITLE
improvement Motor

### ISSUE THREAD

**Issue by Micha7719** [t0nyz0/Bambu-Poop-Conveyor-ESP32#9]
great project, maybe an improvement for the code.
An option to set the motor to run backwards / forwards.
My motor was pre-soldered, but + - swapped. So I had to open the box again and swap the cables

**Comment by t0nyz0** [comment]
Good idea, I'll add that in the next build.

**Comment by Micha7719** [comment]
Maybe some more improvements.

Online Firmware Update

An integration for Home Assistant, I would like a status display in HomeAssistant if the engine is running..
is that possible?

**Comment by t0nyz0** [comment]
I'll look into it, I dont think it would be difficult to add.

**Comment by t0nyz0** [comment]
v1.3.5 includes
- Ability to run motor forward/reverse via settings
- Home assistant support, ability to see if its running, and to manually run, example yaml:
```
rest_command:
bambu_run_motor:
    url: "http://11.0.1.54/run"
    method: POST

sensor:
  - platform: rest
    name: "Bambu Motor Status"
    resource: "http://11.0.1.54/status"
    value_template: "{{ value_json.motor_running }}"
```


- Working on web installer for firmware updates in 1.3.6. Closing this ticket.
